alias: 'Heizung: Wochenend-Modus'
trigger:
  - platform: time
    hours: 00
    minutes: 00
    seconds: 05
  - platform: state
    entity_id: input_boolean.weekend
    from: 'off'
condition:
  - condition: or
    conditions:
    - condition: and
      conditions:
      - condition: time
        weekday:
          - sat
      - condition: state
        entity_id: input_boolean.weekend
        state: 'off'
    - condition: template
      value_template: '{{ trigger.platform == "state" }}'
action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.weekend
#------------------------------------------------
# Office
#------------------------------------------------
  - service: input_number.set_value
    data_template:
      entity_id: input_number.heating_office_day
      value: 21
  - service: input_number.set_value
    data_template:
      entity_id: input_number.heating_office_evening
      value: 20
  - service: input_number.set_value
    data_template:
      entity_id: input_number.heating_office_night
      value: 16
#------------------------------------------------
# Livingroom
#------------------------------------------------
  - service: input_number.set_value
    data_template:
      entity_id: input_number.heating_livingroom_day
      value: 21
  - service: input_number.set_value
    data_template:
      entity_id: input_number.heating_livingroom_evening
      value: 24
  - service: input_number.set_value
    data_template:
      entity_id: input_number.heating_livingroom_night
      value: 16
#------------------------------------------------
# Bedroom
#------------------------------------------------
  - service: input_number.set_value
    data_template:
      entity_id: input_number.heating_bedroom_day
      value: 17
  - service: input_number.set_value
    data_template:
      entity_id: input_number.heating_bedroom_evening
      value: 16
  - service: input_number.set_value
    data_template:
      entity_id: input_number.heating_bedroom_night
      value: 16
#------------------------------------------------
# Kitchen
#------------------------------------------------
  - service: input_number.set_value
    data_template:
      entity_id: input_number.heating_kitchen_morning
      value: 17 
  - service: input_number.set_value
    data_template:
      entity_id: input_number.heating_kitchen_day
      value: 19
  - service: input_number.set_value
    data_template:
      entity_id: input_number.heating_kitchen_evening
      value: 18
  - service: input_number.set_value
    data_template:
      entity_id: input_number.heating_kitchen_night
      value: 16
#------------------------------------------------
# bathroom
#------------------------------------------------
  - service: input_number.set_value
    data_template:
      entity_id: input_number.heating_bathroom_morning
      value: 18
  - service: input_number.set_value
    data_template:
      entity_id: input_number.heating_bathroom_day
      value: 18 
  - service: input_number.set_value
    data_template:
      entity_id: input_number.heating_bathroom_evening
      value: 19
  - service: input_number.set_value
    data_template:
      entity_id: input_number.heating_bathroom_night
      value: 16
