alias: 'Heizungseinstellung Morgens'
hide_entity: 'True'
trigger:
  - platform: time
    hours: 07
    minutes: 00
    seconds: 00
  - platform: state
    entity_id: input_number.heating_bathroom_morning
  - platform: state
    entity_id: input_number.heating_kitchen_morning
  - platform: state
    entity_id: input_boolean.venting
    to: 'off'
condition:
  - condition: and
    conditions:
      - condition: template
        value_template: '{{ 7 <= now().hour < 8 }}'
      - condition: state
        entity_id: input_boolean.weekend
        state: 'off'
      - condition: state
        entity_id: input_boolean.venting
        state: 'off'
action:
  - service: climate.set_temperature
    data_template:
      entity_id: climate.danfoss_bathroom_heating_1
      temperature: '{{ states.input_number.heating_bathroom_morning.state }}'
  - service: climate.set_temperature
    data_template:
      entity_id: climate.danfoss_kitchen_heating_1
      temperature: '{{ states.input_number.heating_kitchen_morning.state }}'
  - service: input_number.set_value
    data_template:
      entity_id: input_number.heating_bathroom
      value: '{{ states.input_number.heating_bathroom_morning.state }}'
  - service: input_number.set_value
    data_template:
      entity_id: input_number.heating_kitchen
      value: '{{ states.input_number.heating_kitchen_morning.state }}'
