alias: 'Switch On Desk Light When MacBook Is Online'
trigger:
  - platform: state
    entity_id: device_tracker.probook
    to: 'home'
    from: 'not_home'
condition:
  - condition: and
    conditions:
      - condition: sun
        after: sunset
        after_offset: '-00:15:00'
      - condition: state
        entity_id: light.buro
        state: 'on'
action:
  service: light.hue_activate_scene
  data:
    group_name: 'Büro'
    scene_name: 'Schreibtisch'
