alias: 'Lights On When Motion Detected'
trigger:
  - platform: state
    entity_id: sensor.fibaro_fgms_livingroom_burglar
    to: '8'
condition:
  - condition: and
    conditions:
      - condition: template
        value_template: '{{ states.sensor.fibaro_fgms_livingroom_luminance.state | float <= 1.0 }}'
      - condition: state
        entity_id: group.livingroom_lights
        state: 'off'
      - condition: template
        value_template: '{{ 17 < now().hour <= 23 }}'
action:
  service: light.hue_activate_scene
  data:
    group_name: 'Wohnzimmer'
    scene_name: 'Musik und Lesen'
