alias: 'Bedroom Window Sensor Tamper Alert'
trigger:
  platform: state
  entity_id: sensor.fibaro_fgk_bedroom_burglar
  to: '3'
  from: '0'
action:
  service: notify.ios_iphone6s
  data:
    message: 'TAMPERING SENSOR IN BEDROOM WAS TRIGGERED!'
    title: 'ALERT'
